language: ruby

before_install:
  - gem install bundler

bundler_args: --jobs=3 --retry=3

cache: bundler

matrix:
  include:
    - rvm: 2.2.0
      env: PUPPET_VERSION=4.0
    - rvm: 2.2.0
      env: PUPPET_VERSION=4.1
    - rvm: 2.2.0
      env: PUPPET_VERSION=4.2
    - rvm: 2.2.0
      env: PUPPET_VERSION=4.3
    - rvm: 2.2.0
      env: PUPPET_VERSION=4.4
    - rvm: 2.2.0
      env: PUPPET_VERSION=4.5
    - rvm: 1.9.3
      env: PUPPET_VERSION=3.8.7
  allow_failures:
    - env: PUPPET_VERSION=4.0
    - env: PUPPET_VERSION=4.1
    - env: PUPPET_VERSION=4.2
    - env: PUPPET_VERSION=4.3
    - env: PUPPET_VERSION=4.4
    - env: PUPPET_VERSION=4.5
